### ISSUE TITLE
Error syncing Angular translations

### ISSUE THREAD

**Issue by simooo985** [rvanbekkum/ps-xliff-sync#2] opened 2020-11-26 09:55 UTC
Hi, first of all thank you for this very useful tool. 
It happens something strange when i try to use it. I have and angular application and i extracted an xlf file named messages.xlf using ng i18n-extract ( it is the file attached to the issue ), i copied and renamed it into messages.it.xlf. Then i run ng i18n-extract again because some translations have been added to the app, so the messages.xlf now contains more entries. Here comes xliff sync tool: when i run 

Sync-XliffTranslations -sourcePath "src\locale\messages.xlf" -targetPath "src\locale\messages.it.xlf"

the file messages.it.xlf is correctly merged, but in the console i get a lot of errors like this 

Exception calling "ImportNode" with "2" argument(s): "Cannot import a null node."
At C:\Program Files\WindowsPowerShell\Modules\XliffSync\1.0.0.0\Model\XlfDocument.ps1:509 char:21
+ ...             $newWhiteSpaceNode = $this.root.OwnerDocument.ImportNode( ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

why? how can i get rid of these errors?

Thank you very much in advance

[messages.zip](https://github.com/rvanbekkum/ps-xliff-sync/files/5601990/messages.zip)

**Comment by rvanbekkum** [comment] 2020-11-26 15:59
Hi @simooo985,
Thank you for filing the issue and providing an example. I will check what the problem is. 😉

**Comment by rvanbekkum** [comment] 2021-03-06 20:10
Hi @simooo985,
A bit of a late reply, but I found out what the issue is.
The module was build specifically for files from the XLIFF Generator that ships with the "AL Compiler for Microsoft Dynamics 365 Business Central apps". The thing is, in these XLIFF files the `xml:space="preserve"` attribute is added to trans-units and so the `NextSibling`-method also treats whitespace as siblings. The PowerShell module was built with the assumption of this always being the behaviour of the `NextSibling`/`PreviousSibling` method, but that is not the case.
I will make a change to take this attribute into account.

**Comment by rvanbekkum** [comment] 2021-03-06 21:46
This has been resolved in v1.1.0.0 which is now available. Thank you for filing the issue!

**Closed by rvanbekkum** 2021-03-06 21:46 UTC
Labels: bug, ships-in-future-update
